### ISSUE TITLE
`Again` Statement

### ISSUE THREAD

**Issue by Zebralt** [oleobal/rockstar-interpreter#1]
I was thinking of implementing Increment/Decrement operators as described in the spec.
Then I had an idea : wouldn't it be cool to be able to repeat the last instruction with the `again` keyword ? Juts in specific cases of course :

    This guy is messing with you (poetic literal : 743)
    Knock this guy down (742)
    Knock this guy down again (741) ('again' not counted as a keyword here)
    And again (740)
    And again (739)

It should be taken into account only in the case where it is the only keyword in a line. This 'callback' to last operation could also be restrained to the block rather than the entire program.

That and various synonyms (`once more`, `more`) to improve expressivity and available vocalubary.

**Comment by oleobal** [comment]
I'm all for additions (improvements, frankly) to the spec, but they should be toggleable and off by default. That's just good practice.

That, or we fork Rockstar and find a better name, but that won't be easy.

**Comment by oleobal** [comment]
Closing to avoid having a hanging issue until we are done with the spec.
