### ISSUE TITLE
Remove comments ?

### ISSUE THREAD

**Issue by oleobal** [oleobal/rockstar-interpreter#7]
I suggest we don't leave commented out code, we have it under source control so it won't be lost, and it hinders readability.

case in point : 
https://github.com/oleobal/rockstar-interpreter/blob/29f2095eb02033a0276f0181907def5a7f0c06c4/rockstar.py#L306

**Comment by Zebralt** [comment]
I'm on it : 318c1d14ebef6b469c2b9001335a3d08db962d40.
